from enum import Enum


class ActionType(Enum):
    STABILIZATION_ACTION = "STABILIZATION_ACTION"
    BODY_MOVEMENT_ACTION = "BODY_MOVEMENT_ACTION"
    NO_OP_ACTION = "NO_OP_ACTION"
    DISPLAY_ACTION = "DISPLAY_ACTION"
    SOUND_ACTION = "SOUND_ACTION"
    LAMBDA_ACTION = "LAMBDA_ACTION"
