from enum import Enum


class ActionType(Enum):
    BODY_MOVEMENT_ACTION = "BODY_MOVEMENT_ACTION"
    NO_OP = "NO_OP"
    DISPLAY_ACTION = "DISPLAY_ACTION"
    LAMBDA_ACTION = "LAMBDA_ACTION"
    SOUND_ACTION = "SOUND_ACTION"
    STABILIZATION_ACTION = "STABILIZATION_ACTION"
    MOVE_ACTION = "MOVE_ACTION"
    # TODO: Add here
