name: Catkin

on:
  push:
    branches:
      - dev
      - main
      - testWorkflow
  pull_request:
    branches:
      - dev
      - main

jobs:
  catkin:
    name: catkin
    runs-on: ubuntu-latest
  
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Setup catkin
        uses: betwo/github-setup-catkin@master
        with:
          ros-version: 'noetic'
          workspace: '$GITHUB_WORKSPACE'
      - run: catkin_make_isolated
