name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: ${{ github.event_name != 'pull_request' }}
          continue_on_error: ${{ github.event_name != 'pull_request' }}
          black: true
          black_args: "--color ${{ (github.event_name == 'pull_request' && '--diff --check') || '' }}"
          flake8: true
          flake8_args: "--max-line-length=88 --extend-ignore=E203,E501 --select=C,E,F,W,B,B950"

