name: Lint

on: [push, pull_request]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install black flake8

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          continue_on_error: false
          black: true
          black_args: "--line-length=120 --color --diff --check"
          black_dir: src/enamour
          flake8: true
          flake8_args: "--max-line-length=120 --extend-ignore=E203,E501,F841 --select=C,E,F,W,B,B950" #Remove F841(ignore unused variables) later
          flake8_dir: src/enamour

